"""Revisión fundacional del esquema (Fase 9.5, Bloque B).

Esta es la ÚNICA revisión de la que parte el historial de Alembic a partir de
ahora. Sustituye a la cadena `0001_esquema_inicial` -> `0002_multitenancy` ->
`0003_notificaciones` -> `0004_ampliar_auditoria_quien`, que existe en
paralelo hasta que el Bloque D de la Fase 9.5 retire esas cuatro revisiones.

`down_revision = None` porque esta revisión declara el esquema completo tal
cual existe hoy (21 tablas), generada por `autogenerate` contra la metadata
real de `app/models.py` con un directorio de versiones vacío y una base
SQLite recién creada: no encadena con ninguna revisión anterior a propósito,
precisamente para dejar de depender de la cadena 0001-0004 (que no se puede
aplicar de forma fiable sobre una base limpia — ver
`docs/PLAN_REPARACION_MIGRACIONES.md`).

Nota técnica: `autogenerate` renderiza `sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql')`
pero solo importa `sqlalchemy as sa` y `sqlalchemy.dialects.postgresql`, no
`Text` a secas — el fichero generado no cargaba (`NameError: name 'Text' is
not defined`). Se corrigió a `sa.Text()` en las 19 columnas con variante
JSONB; es la única corrección de contenido aplicada sobre lo que produjo
`autogenerate`, además de renombrar el identificador y el fichero.

Revision ID: 0005
Revises:
Create Date: 2026-07-26 23:49:39.883890
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0005"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quien', sa.String(length=120), nullable=True),
    sa.Column('cuando', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entidad', sa.String(length=32), nullable=False),
    sa.Column('entidad_id', sa.String(length=36), nullable=False),
    sa.Column('accion', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparable',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipologia', sa.String(length=24), nullable=False),
    sa.Column('municipio', sa.String(length=80), nullable=True),
    sa.Column('superficie_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('precio_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=True),
    sa.Column('origen', sa.String(length=24), nullable=True),
    sa.Column('fecha_dato', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparable_municipio'), 'comparable', ['municipio'], unique=False)
    op.create_index(op.f('ix_comparable_tipologia'), 'comparable', ['tipologia'], unique=False)
    op.create_table('fuente_subasta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('perfil', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('organizacion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametro',
    sa.Column('clave', sa.String(length=64), nullable=False),
    sa.Column('ambito', sa.String(length=32), nullable=False),
    sa.Column('vigente_desde', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fuente_legal', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('clave', 'ambito', 'vigente_desde')
    )
    op.create_table('perfil_inversion',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('parametros', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('regla',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('categoria', sa.String(length=16), nullable=False),
    sa.Column('prioridad', sa.SmallInteger(), nullable=False),
    sa.Column('definicion', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autor', sa.String(length=80), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('codigo', 'version')
    )
    op.create_index(op.f('ix_regla_categoria'), 'regla', ['categoria'], unique=False)
    op.create_table('subasta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fuente_codigo', sa.String(length=32), nullable=False),
    sa.Column('identificador_externo', sa.String(length=120), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('valor_subasta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('puja_minima', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tramo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposito_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('subastas_desiertas_previas', sa.SmallInteger(), nullable=False),
    sa.Column('datos_brutos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subasta_estado'), 'subasta', ['estado'], unique=False)
    op.create_index(op.f('ix_subasta_fuente_codigo'), 'subasta', ['fuente_codigo'], unique=False)
    op.create_table('activo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subasta_id', sa.String(length=36), nullable=False),
    sa.Column('lote', sa.SmallInteger(), nullable=False),
    sa.Column('tipologia', sa.String(length=24), nullable=False),
    sa.Column('ref_catastral', sa.String(length=24), nullable=True),
    sa.Column('finca_registral', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('municipio', sa.String(length=80), nullable=True),
    sa.Column('provincia', sa.String(length=40), nullable=True),
    sa.Column('ccaa', sa.String(length=32), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('superficie_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('anio_construccion', sa.SmallInteger(), nullable=True),
    sa.Column('estado_conservacion', sa.String(length=16), nullable=True),
    sa.Column('es_vivienda_habitual', sa.Boolean(), nullable=True),
    sa.Column('vpo', sa.Boolean(), nullable=False),
    sa.Column('atributos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['subasta_id'], ['subasta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activo_municipio'), 'activo', ['municipio'], unique=False)
    op.create_index(op.f('ix_activo_ref_catastral'), 'activo', ['ref_catastral'], unique=False)
    op.create_index(op.f('ix_activo_subasta_id'), 'activo', ['subasta_id'], unique=False)
    op.create_index(op.f('ix_activo_tipologia'), 'activo', ['tipologia'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('hash_pwd', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=16), nullable=False),
    sa.Column('organizacion_id', sa.String(length=36), nullable=True),
    sa.Column('rol_org', sa.String(length=16), nullable=False),
    sa.Column('es_superadmin', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_organizacion_id'), 'usuario', ['organizacion_id'], unique=False)
    op.create_table('alerta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('criterios', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerta_usuario_id'), 'alerta', ['usuario_id'], unique=False)
    op.create_table('analisis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizacion_id', sa.String(length=36), nullable=True),
    sa.Column('activo_id', sa.String(length=36), nullable=True),
    sa.Column('perfil_codigo', sa.String(length=32), nullable=False),
    sa.Column('version_reglas', sa.String(length=16), nullable=False),
    sa.Column('version_parametros', sa.String(length=16), nullable=False),
    sa.Column('entrada', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hechos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resultado', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ici', sa.SmallInteger(), nullable=True),
    sa.Column('icu', sa.SmallInteger(), nullable=True),
    sa.Column('ra', sa.SmallInteger(), nullable=True),
    sa.Column('ico', sa.SmallInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activo_id'], ['activo.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_activo_id'), 'analisis', ['activo_id'], unique=False)
    op.create_index(op.f('ix_analisis_creado_en'), 'analisis', ['creado_en'], unique=False)
    op.create_index(op.f('ix_analisis_organizacion_id'), 'analisis', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_analisis_perfil_codigo'), 'analisis', ['perfil_codigo'], unique=False)
    op.create_table('carga',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activo_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('rango', sa.SmallInteger(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('es_anterior', sa.Boolean(), nullable=False),
    sa.Column('se_purga', sa.Boolean(), nullable=False),
    sa.Column('verificada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activo_id'], ['activo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carga_activo_id'), 'carga', ['activo_id'], unique=False)
    op.create_table('codigo_telegram',
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_codigo_telegram_usuario_id'), 'codigo_telegram', ['usuario_id'], unique=False)
    op.create_table('preferencias_notificacion',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('canales', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('modo', sa.String(length=16), nullable=False),
    sa.Column('hora_digest', sa.SmallInteger(), nullable=False),
    sa.Column('silencio_inicio', sa.SmallInteger(), nullable=True),
    sa.Column('silencio_fin', sa.SmallInteger(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.Column('comunicaciones_activas', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('decision',
    sa.Column('analisis_id', sa.String(length=36), nullable=False),
    sa.Column('semaforo', sa.String(length=8), nullable=False),
    sa.Column('p_ideal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p_objetivo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p_limite', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margen_seguridad', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('p_adj_esperado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rvc', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('vetos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('condiciones', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ),
    sa.PrimaryKeyConstraint('analisis_id')
    )
    op.create_index(op.f('ix_decision_semaforo'), 'decision', ['semaforo'], unique=False)
    op.create_table('escenario',
    sa.Column('analisis_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=12), nullable=False),
    sa.Column('probabilidad', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('vs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('plazo_meses', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('coste_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('beneficio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('roi', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ),
    sa.PrimaryKeyConstraint('analisis_id', 'nombre')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('alerta_id', sa.String(length=36), nullable=True),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alerta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacion_estado'), 'notificacion', ['estado'], unique=False)
    op.create_index(op.f('ix_notificacion_usuario_id'), 'notificacion', ['usuario_id'], unique=False)
    op.create_table('regla_disparada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analisis_id', sa.String(length=36), nullable=False),
    sa.Column('regla_codigo', sa.String(length=32), nullable=False),
    sa.Column('regla_version', sa.String(length=16), nullable=False),
    sa.Column('efecto', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidencias', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regla_disparada_analisis_id'), 'regla_disparada', ['analisis_id'], unique=False)
    op.create_table('resultado_real',
    sa.Column('analisis_id', sa.String(length=36), nullable=False),
    sa.Column('precio_adjudicacion', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('adjudicatario_propio', sa.Boolean(), nullable=True),
    sa.Column('coste_real_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('precio_venta_real', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('plazo_real_meses', sa.SmallInteger(), nullable=True),
    sa.Column('incidencias', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ),
    sa.PrimaryKeyConstraint('analisis_id')
    )
    op.create_table('riesgo_evaluado',
    sa.Column('analisis_id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=16), nullable=False),
    sa.Column('probabilidad', sa.SmallInteger(), nullable=False),
    sa.Column('impacto', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('nivel', sa.String(length=8), nullable=False),
    sa.Column('mitigable', sa.Boolean(), nullable=False),
    sa.Column('condiciones', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidencias', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ),
    sa.PrimaryKeyConstraint('analisis_id', 'dimension')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riesgo_evaluado')
    op.drop_table('resultado_real')
    op.drop_index(op.f('ix_regla_disparada_analisis_id'), table_name='regla_disparada')
    op.drop_table('regla_disparada')
    op.drop_index(op.f('ix_notificacion_usuario_id'), table_name='notificacion')
    op.drop_index(op.f('ix_notificacion_estado'), table_name='notificacion')
    op.drop_table('notificacion')
    op.drop_table('escenario')
    op.drop_index(op.f('ix_decision_semaforo'), table_name='decision')
    op.drop_table('decision')
    op.drop_table('preferencias_notificacion')
    op.drop_index(op.f('ix_codigo_telegram_usuario_id'), table_name='codigo_telegram')
    op.drop_table('codigo_telegram')
    op.drop_index(op.f('ix_carga_activo_id'), table_name='carga')
    op.drop_table('carga')
    op.drop_index(op.f('ix_analisis_perfil_codigo'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_organizacion_id'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_creado_en'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_activo_id'), table_name='analisis')
    op.drop_table('analisis')
    op.drop_index(op.f('ix_alerta_usuario_id'), table_name='alerta')
    op.drop_table('alerta')
    op.drop_index(op.f('ix_usuario_organizacion_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_activo_tipologia'), table_name='activo')
    op.drop_index(op.f('ix_activo_subasta_id'), table_name='activo')
    op.drop_index(op.f('ix_activo_ref_catastral'), table_name='activo')
    op.drop_index(op.f('ix_activo_municipio'), table_name='activo')
    op.drop_table('activo')
    op.drop_index(op.f('ix_subasta_fuente_codigo'), table_name='subasta')
    op.drop_index(op.f('ix_subasta_estado'), table_name='subasta')
    op.drop_table('subasta')
    op.drop_index(op.f('ix_regla_categoria'), table_name='regla')
    op.drop_table('regla')
    op.drop_table('perfil_inversion')
    op.drop_table('parametro')
    op.drop_table('organizacion')
    op.drop_table('fuente_subasta')
    op.drop_index(op.f('ix_comparable_tipologia'), table_name='comparable')
    op.drop_index(op.f('ix_comparable_municipio'), table_name='comparable')
    op.drop_table('comparable')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
