/**
 * Fase 5K-B — nombres, unidades y orden de la entrada de un análisis («Datos de
 * entrada»). Mismas palabras que el asistente de alta; las secciones siguen sus pasos.
 * Una ruta que no esté aquí se muestra con su clave humanizada: no se pierde nada.
 */
import type { Etiqueta } from "@/lib/presentacion-valores";

const SI_NO_CONSTA = { si: "Sí", no: "No", no_consta: "No consta" };

/** Secciones de la entrada, en el orden de los pasos del asistente. */
export const SECCIONES_ENTRADA: { titulo: string; claves: string[] }[] = [
  { titulo: "Datos generales", claves: ["perfil", "subasta"] },
  { titulo: "Tipo de activo y ubicación", claves: ["activo"] },
  { titulo: "Datos registrales", claves: ["cargas", "ocupacion"] },
  { titulo: "Datos urbanísticos", claves: ["urbanistico"] },
  { titulo: "Valoraciones y mercado", claves: ["comparables", "zona"] },
  { titulo: "Costes", claves: ["costes"] },
  { titulo: "Reforma", claves: ["reforma"] },
  { titulo: "Financiación", claves: ["financiacion", "rentista"] },
  { titulo: "Validación (documentación)", claves: ["documentos"] },
];

export const ETIQUETAS_ENTRADA: Record<string, Etiqueta> = {
  perfil: { etiqueta: "Perfil de inversión" },
  subasta: { etiqueta: "Subasta" },
  "subasta.fuente": { etiqueta: "Fuente de la subasta" },
  "subasta.valor_subasta": { etiqueta: "Valor de subasta", unidad: "€" },
  "subasta.puja_minima": { etiqueta: "Puja mínima", unidad: "€" },
  "subasta.tramo": { etiqueta: "Tramo de puja", unidad: "€" },
  "subasta.deposito_pct": { etiqueta: "Depósito", fraccion: true },
  "subasta.deposito_importe": { etiqueta: "Depósito escrito en euros", unidad: "€" },
  "subasta.fecha_cierre": { etiqueta: "Fecha de cierre" },
  "subasta.horas_hasta_cierre": { etiqueta: "Horas hasta el cierre", unidad: "h" },
  "subasta.subastas_desiertas_previas": { etiqueta: "Subastas previas desiertas" },
  "subasta.identificador_externo": { etiqueta: "Identificador / expediente" },
  "subasta.url": { etiqueta: "Enlace" },
  "subasta.procedimiento": { etiqueta: "Tipo de procedimiento", valores: {
    judicial: "Judicial", aeat: "Agencia Tributaria (AEAT)", tgss: "Seguridad Social (TGSS)", notarial: "Subasta notarial",
    extrajudicial: "Venta extrajudicial hipotecaria", concursal: "Concursal", no_aplica: "No aplica (venta bancaria o privada)" } },
  "subasta.regimen_judicial": { etiqueta: "Inicio del procedimiento judicial", valores: {
    posterior: "El 3-4-2025 o después", anterior: "Antes del 3-4-2025", no_se: "No sé" } },
  "subasta.cantidad_reclamada": { etiqueta: "Cantidad reclamada", unidad: "€" },

  activo: { etiqueta: "Activo" },
  "activo.tipologia": { etiqueta: "Tipología" },
  "activo.superficie_m2": { etiqueta: "Superficie construida", unidad: "m²" },
  "activo.estado_conservacion": { etiqueta: "Estado de conservación", valores: { desconocido: "No consta" } },
  "activo.anio_construccion": { etiqueta: "Año de construcción" },
  "activo.direccion": { etiqueta: "Dirección" },
  "activo.municipio": { etiqueta: "Municipio" },
  "activo.provincia": { etiqueta: "Provincia" },
  "activo.ccaa": { etiqueta: "Comunidad autónoma" },
  "activo.lat": { etiqueta: "Latitud" },
  "activo.lng": { etiqueta: "Longitud" },
  "activo.ref_catastral": { etiqueta: "Referencia catastral" },
  "activo.finca_registral": { etiqueta: "Finca registral" },
  "activo.es_vivienda_habitual": { etiqueta: "Vivienda habitual (casilla anterior a la 5J-1)" },
  "activo.vivienda_habitual_ejecutado": { etiqueta: "¿Vivienda habitual del ejecutado?", valores: SI_NO_CONSTA },
  "activo.vpo": { etiqueta: "Vivienda de protección oficial (VPO)" },
  "activo.vpo_precio_max_legal": { etiqueta: "Precio máximo legal VPO", unidad: "€" },
  "activo.atributos": { etiqueta: "Atributos adicionales" },

  cargas: { etiqueta: "Cargas" },
  "cargas[].tipo": { etiqueta: "Tipo" },
  "cargas[].importe": { etiqueta: "Importe", unidad: "€" },
  "cargas[].es_anterior": { etiqueta: "Anterior al crédito del actor" },
  "cargas[].se_purga": { etiqueta: "Se purga" },
  "cargas[].verificada": { etiqueta: "Verificada" },
  "cargas[].prohibicion_disponer": { etiqueta: "Prohibición de disponer" },
  "cargas[].condicion_resolutoria": { etiqueta: "Condición resolutoria" },
  ocupacion: { etiqueta: "Situación posesoria" },
  "ocupacion.estado": { etiqueta: "Ocupación", valores: { desconocida: "No consta", vacio: "Vacío" } },
  "ocupacion.renta_mensual": { etiqueta: "Renta actual", unidad: "€/mes" },
  "ocupacion.fecha_contrato": { etiqueta: "Fecha del contrato" },

  urbanistico: { etiqueta: "Urbanismo" },
  "urbanistico.uso_compatible": { etiqueta: "Uso compatible con la norma zonal" },
  "urbanistico.fuera_ordenacion": { etiqueta: "Fuera de ordenación" },
  "urbanistico.orden_demolicion": { etiqueta: "Orden de demolición" },
  "urbanistico.suelo_protegido": { etiqueta: "Suelo protegido" },
  "urbanistico.cargas_urbanizacion": { etiqueta: "Cargas de urbanización", unidad: "€" },
  "urbanistico.servidumbres_incompatibles": { etiqueta: "Servidumbres incompatibles" },
  "urbanistico.zona_inundable_alta": { etiqueta: "Zona inundable (riesgo alto)" },

  comparables: { etiqueta: "Comparables" },
  "comparables[].precio_m2": { etiqueta: "Precio", unidad: "€/m²" },
  "comparables[].estado": { etiqueta: "Estado" },
  "comparables[].origen": { etiqueta: "Origen", valores: { portal_oferta: "Oferta en portal" } },
  "comparables[].meses_antiguedad": { etiqueta: "Antigüedad", unidad: "meses" },
  "comparables[].superficie_m2": { etiqueta: "Superficie", unidad: "m²" },
  zona: { etiqueta: "Zona" },
  "zona.macro": { etiqueta: "Mercado macro" },
  "zona.macro.tendencia_5a_pct": { etiqueta: "Tendencia de precios (media 5 años)", unidad: "%/año" },
  "zona.macro.stock_meses": { etiqueta: "Stock", unidad: "meses" },
  "zona.macro.dom_venta_dias": { etiqueta: "Días en el mercado (venta)", unidad: "días" },
  "zona.macro.dom_alquiler_dias": { etiqueta: "Días en el mercado (alquiler)", unidad: "días" },
  "zona.macro.crecimiento_pobl_5a_pct": { etiqueta: "Crecimiento de la población (5 años)", unidad: "%" },
  "zona.macro.renta_hogar": { etiqueta: "Renta media por hogar", unidad: "€/año" },
  "zona.macro.y_zona_pct": { etiqueta: "Rentabilidad neta de la zona", unidad: "%" },
  "zona.micro": { etiqueta: "Indicadores micro (0-100)" },
  "zona.precio_m2_p85": { etiqueta: "Precio del percentil 85 de la zona", unidad: "€/m²" },

  costes: { etiqueta: "Costes" },
  "costes.regimen_fiscal": { etiqueta: "Régimen fiscal", valores: { auto: "Automático (lo decide el motor)" } },
  "costes.transmitente_empresario": { etiqueta: "El transmitente es empresario" },
  "costes.primera_entrega": { etiqueta: "Primera entrega" },
  "costes.comprador_deduce_iva": { etiqueta: "El comprador deduce el IVA" },
  "costes.itp_tipo_override": { etiqueta: "Tipo de ITP indicado", fraccion: true },
  "costes.valor_referencia_catastral": { etiqueta: "Valor de referencia del Catastro", unidad: "€" },
  "costes.valor_declarado": { etiqueta: "Valor declarado", unidad: "€" },
  "costes.atrasos_comunidad_ibi": { etiqueta: "Atrasos de comunidad e IBI", unidad: "€" },
  "costes.adquisicion_fija_override": { etiqueta: "Costes fijos de adquisición", unidad: "€" },
  "costes.tenencia_mensual": { etiqueta: "Tenencia", unidad: "€/mes" },
  "costes.plusvalia_municipal_estimada": { etiqueta: "Plusvalía municipal estimada", unidad: "€" },

  reforma: { etiqueta: "Reforma" },
  "reforma.nivel_override": { etiqueta: "Nivel de reforma indicado" },
  "reforma.visita_interior": { etiqueta: "Visita interior realizada" },
  "reforma.k_provincia": { etiqueta: "Coeficiente provincial", unidad: "×" },
  "reforma.coste_m2_override": { etiqueta: "Coste de obra indicado", unidad: "€/m²" },
  "reforma.partidas_extra": { etiqueta: "Partidas extra", unidad: "€" },

  financiacion: { etiqueta: "Financiación" },
  "financiacion.tipo": { etiqueta: "Estructura de pago", valores: { cash: "Fondos propios", hipoteca: "Hipoteca" } },
  "financiacion.preaprobada": { etiqueta: "Financiación preaprobada" },
  "financiacion.ltv": { etiqueta: "Financiación sobre el valor (LTV)", fraccion: true },
  "financiacion.interes_anual_pct": { etiqueta: "Interés anual", unidad: "%" },
  rentista: { etiqueta: "Alquiler (perfil rentista)" },
  "rentista.renta_mensual_estimada": { etiqueta: "Renta estimada", unidad: "€/mes" },
  "rentista.vacancia_pct": { etiqueta: "Vacancia", unidad: "%" },
  "rentista.ibi_anual": { etiqueta: "IBI", unidad: "€/año" },
  "rentista.comunidad_mensual": { etiqueta: "Comunidad", unidad: "€/mes" },
  "rentista.seguro_anual": { etiqueta: "Seguro", unidad: "€/año" },
  "rentista.mantenimiento_pct_renta": { etiqueta: "Mantenimiento", unidad: "% de la renta" },
  "rentista.gestion_pct_renta": { etiqueta: "Gestión", unidad: "% de la renta" },

  documentos: { etiqueta: "Documentación" },
  "documentos.nota_simple": { etiqueta: "Nota simple" },
  "documentos.nota_simple_dias": { etiqueta: "Antigüedad de la nota simple", unidad: "días" },
  "documentos.cert_cargas": { etiqueta: "Certificación de cargas" },
  "documentos.posesion_verificada": { etiqueta: "Posesión verificada" },
  "documentos.avaluo": { etiqueta: "Avalúo" },
  "documentos.fotos_interior_o_visita": { etiqueta: "Fotos interiores o visita" },
  "documentos.fotos_exterior": { etiqueta: "Fotos exteriores" },
  "documentos.cert_comunidad": { etiqueta: "Certificado de la comunidad" },
  "documentos.recibo_ibi": { etiqueta: "Recibo del IBI" },
  "documentos.ite_cee": { etiqueta: "ITE y certificado energético" },
  "documentos.catastro_conciliado": { etiqueta: "Catastro conciliado" },
  "documentos.inconsistencias": { etiqueta: "Inconsistencias", valores: {
    superficie_inconsistente: "Superficie inconsistente", cargas_mismatch: "Cargas que no cuadran",
    tasacion_anomala: "Tasación anómala" } },
};
